### ISSUE TITLE
double check randomizer push

### ISSUE THREAD

**Issue by patrickjcolgan** [patrickjcolgan/col_index#41]
medium sized bug: while fixing some weird bug that returned no results if user inputs 89k, I noticed that sometimes (maybe always) the randomizer doesn’t push 5 results even though there are more objects in `resultsArr`

[

**Comment by ilikesounds** [comment]
Resolved in https://github.com/patrickjcolgan/col_index/commit/4c019b0662c7e50e6630ff2c25dcb41254eaf42a
